"""empty message

Revision ID: 3275038473b7
Revises: 0fd05ce2c513
Create Date: 2020-11-20 13:19:27.487181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3275038473b7'
down_revision = '0fd05ce2c513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'])
    op.drop_column('cart', 'customer_id')
    op.add_column('user', sa.Column('is_customer', sa.Boolean(), nullable=True))
    op.drop_column('user', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_customer')
    op.add_column('cart', sa.Column('customer_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'user_id')
    # ### end Alembic commands ###
